### PR TITLE
Add dapla-gcp-jupyter to localstack

### PR DESCRIPTION
**Pull request by bjornandre**
It would be great if you could test that the following make targets still work:

make build-all
make start-all
make open-jupyter

And in the end test that Jupyter still work - and integrates with other services

### CODE REVIEW

**Comment by fnh-ssb** [comment]
sure

**Comment by fnh-ssb** [comment]
> It would be great if you could test that the following make targets still work:
> 
> make build-all
> make start-all
> make open-jupyter
> 
> And in the end test that Jupyter still work - and integrates with other services

sure

**Comment by fnh-ssb** [comment]
LGTM. but I encounter some spark session problems: it seems my environment can not load the spark automatically.
I need to manually add:
from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession
sc = SparkContext('local')
spark = SparkSession(sc)

but it seems not correct, since it gives a 

AttributeError                            Traceback (most recent call last)
<ipython-input-9-ba11b257527a> in <module>
----> 1 ds = spark.read.path("/ske/skatt/person/fastsatt/rådata/2019v1.0.1")
      2 bilmerke_og_innskudd = ds.select("skattemeldingUtflatet.personidentifikator", "skattemeldingUtflatet.kjoeretoey", "skattemeldingUtflatet.konto")\
      3     .withColumnRenamed("konto", "kontoer")\
      4     .withColumnRenamed("kjoeretoey", "biler")\
      5     .withColumn("konto", explode("kontoer"))\

AttributeError: 'DataFrameReader' object has no attribute 'path'

any clues to load the spark in jupyterlab?

**Comment by bjornandre** [comment]
> LGTM. but I encounter some spark session problems: it seems my environment can not load the spark automatically.
> I need to manually add:
> from pyspark.context import SparkContext
> from pyspark.sql.session import SparkSession
> sc = SparkContext('local')
> spark = SparkSession(sc)
> 
> but it seems not correct, since it gives a
> 
> AttributeError Traceback (most recent call last)
> in 
> ----> 1 ds = spark.read.path("/ske/skatt/person/fastsatt/rådata/2019v1.0.1")
> 2 bilmerke_og_innskudd = ds.select("skattemeldingUtflatet.personidentifikator", "skattemeldingUtflatet.kjoeretoey", "skattemeldingUtflatet.konto")
> 3 .withColumnRenamed("konto", "kontoer")
> 4 .withColumnRenamed("kjoeretoey", "biler")
> 5 .withColumn("konto", explode("kontoer"))\
> 
> AttributeError: 'DataFrameReader' object has no attribute 'path'
> 
> any clues to load the spark in jupyterlab?

You need to run the Pyspark kernel

**Pull request merged**
